name: Build Windows

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build OpenRGB
      run: |
        qmake OpenRGB.pro CONFIG-=debug_and_release CONFIG+=release
        nmake

    - name: Deploy Qt Dependencies
      run: |
        windeployqt --no-patchqt --no-quick-import --no-translations --no-system-d3d-compiler --no-compiler-runtime --no-opengl-sw release/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OpenRGB-Windows-64bit
        path: release/
